### ISSUE TITLE
Extend ZeTime API

### ISSUE THREAD

**Issue by Lightwars** [Blightbuster/ZeOpenTime#1]
If you like you could just check out the code from [Gadgetbridge](https://github.com/Freeyourgadget/Gadgetbridge), which has support for the ZeTime and you can send notifications to the watch, control the music from the watch, set serveral preferneces of the watch and so on.

The interesting things happen [here](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/zetime/ZeTimeDeviceSupport.java).

**Comment by Blightbuster** [comment]
Thanks I didnt knew about it before. This is probably what every one should be using if they are serius about it.
